config/routes.rb
MhtApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Mindful Health"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container" id="top_container">
      <div class="row-fluid">
      
        <div class="span3">
          <%= link_to "Mindful Health", root_path, id: "logo" %>
        </div>
        <nav>
          <ul class="nav pull-right" id="home_about_nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Meet the Team", about_path %></li>
            <% if signed_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account&nbsp; <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <!-- <li><%= link_to "Sign in", signin_path %></li> -->
            <% end %>
          </ul>
        </nav>



      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>The Mindful Health Team</h1>
<div class="row team">
	<div class="col-sm-3">      
    <img src="http://s3.amazonaws.com/mht_assets/images/about_pic_fernando.png">
    </div><!-- /.span4 -->
    <div class="col-sm-7 col-md-8 col-lg-9 pull-right about">
        <h4><u>Chris Fernandez</u></h4>
        <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
    </div>    
</div><!-- /.row -->
<div class="row team">
	<div class="col-sm-3">      
    <img src="http://s3.amazonaws.com/mht_assets/images/about_pic_jared.png">
    </div><!-- /.span4 -->
    <div class="col-sm-7 col-md-8 col-lg-9 pull-right about">
    <h4><u>Jared Buckner</u></h4>
    <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
    </div>    
</div><!-- /.row -->
<div class="row team">
	<div class="col-sm-3">      
    <img src="http://s3.amazonaws.com/mht_assets/images/about_pic_olivia.png">
    </div><!-- /.span4 -->
    <div class="col-sm-7 col-md-8 col-lg-9 pull-right about">
    <h4><u>Olivia Rice</u></h4>
    <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
    </div>    
</div><!-- /.row -->
<div class="row team">
	<div class="col-sm-3">      
    <img src="http://s3.amazonaws.com/mht_assets/images/about_pic_mrglattard.png">
    </div><!-- /.span4 -->
    <div class="col-sm-7 col-md-8 col-lg-9 pull-right about">
    <h4><u>Mr. Glattard</u></h4>
    <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
    </div>    
</div><!-- /.row -->

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Mindful Health</h1>
<p>
  This is the Contact page for Mindful Health
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit" id="home_page_hero_unit">
  <!--<%= image_tag("doc.jpg", :id => "main_pic") %>--> 
  <div class="row-fluid">
    <div class="header pull-right" id="mh">
      <h1>Mindful Health</h1>
      <h2>Better tools for better care</h2>
    </div>
  </div>
  <!--<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %> -->
</div>

 <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container">
      <div class="row" id="solution_row">
        
          <h3>Our Solution</h3>
       
      </div>
      <!-- Three columns of text below the carousel -->
      <div class="row center">
        <div class="col-md-4">
          <img class="img-circle" data-src="holder.js/140x140">
          <h2>Easy-to-use health wearables</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
        </div><!-- /.span4 -->
        <div class="col-md-4">
          <img class="img-circle" data-src="holder.js/140x140">
          <h2>Software that keeps you connected</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        </div><!-- /.span4 -->
        <div class="col-md-4">
          <img class="img-circle" data-src="holder.js/140x140">
          <h2>Redefine preventative care</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        </div><!-- /.span4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <!-- /END THE FEATURETTES -->




    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>


<div class="container signin">
  <form role="form">
    <div class="form-group">
      <label type="text" for="inputName" class="control-label">Name:</label>
      <input type="name" class="form-control" id="inputName" placeholder="Name">
    </div>
    <div class="form-group">
      <label for="inputEmail" class="control-label">Email:</label>
      <input type="email" class="form-control" id="inputEmail" placeholder="Email">
    </div>
    <div class="form-group">
      <label for="inputPassword" class="control-label">Password:</label>
      <input type="password" class="form-control" id="inputPassword" placeholder="Password">
    </div>
    <div class="form-group">
      <label for="inputConfirmation" class="control-label">Confirmation:</label>
      <input type="confirmation" class="form-control" id="inputConfirmation" placeholder="Password Confirmation">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-lg btn-primary">Sign Up!</button>
  </div>
  </form>
</div>

<!--<div class="form-horizontal" role="form">
  <div class="form-group">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
  </div>
      
          <%= f.text_field :name %>
     
      <div class="form-group">
          <%= f.label :email %>
  
      
        <%= f.text_field :email %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
    
      
        <%= f.password_field :password %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
      
     
        <%= f.password_field :password_confirmation %>
      </div>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>-->

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div id="wrapper">
      <!-- Sidebar -->
      <div id="sidebar-wrapper">
        <ul class="sidebar-nav" id="side-nav">
          <li>
            <a href="#" class="text-left">
                          <b>
                            Patients
                          </b>
                        </a>
          </li>
          <li>
            <a href="#">
                          Patient 1
                        </a>
          </li>
          <li>
            <a href="#">
                          Patient 2
                        </a>
          </li>
          <li>
            <a href="#">
                          Patient 3
                        </a>
          </li>
          <li>
            <a href="#">
                          Patient 4
                        </a>
          </li>
        </ul>
      </div>
      <!-- Page content -->
      <div id="page-content-wrapper">
        <!-- Keep all page content within the page-content inset div! -->
        <div class="page-content inset">
          <div class="row" id="row-top">
            <div class="col-md-12">
              <p class="lead text-center">
              </p>
              <center>
                <h2>
                  Mindful Health Dashboard Overview
                </h2>
              </center>
              <p>
              </p>
              <h4>
                Care team on staff: 4
              </h4>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="40"
                aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                  <span class="sr-only">40% Complete (success)</span>
                </div>
              </div>
              <h4>
                Green patients: 8
              </h4>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
                aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                  <span class="sr-only">20% Complete</span>
                </div>
              </div>
              <h4>
                Cautionary patients: 6
              </h4>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
                aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                  <span class="sr-only">60% Complete (warning)</span>
                </div>
              </div>
              <h4>
                Critical patients: 2
              </h4>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80"
                aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                  <span class="sr-only">80% Complete</span>
                </div>
              </div>
              <p>
              </p>
            </div>
            <div class="col-md-6">
              <div class="jumbotron">
                <center>
                  <h2>
                    Manage Patients
                  </h2>
                  <p>
                    Add patients, remove exsisting patients, and more.
                  </p>
                  <p>
                    <a class="btn btn-primary btn-lg" role="button">Manage Now</a>
                  </p>
                </center>
              </div>
              <p>
              </p>
            </div>
            <div class="col-md-6">
              <div class="jumbotron">
                <center>
                  <h2>
                    Manage Care Team
                  </h2>
                  <p>
                    Configure care team memberships and profiles.
                  </p>
                  <p>
                    <a class="btn btn-primary btn-lg" role="button">Manage Now</a>
                  </p>
                </center>
              </div>
              <p>
              </p>
            </div>
            <div class="col-md-4">
              <p class="well well-sm">
                <b>Recent user activity</b>
                <a href="#" class="btn btn-xs pull-right btn-info">Review Activity</a>
              </p>
            </div>
            <div class="col-md-4">
              <p class="well well-sm">
                <b>Physician on staff: Dr. Robertson</b>
                <a href="#" class="btn btn-xs pull-right btn-info">Contact Now</a>
              </p>
            </div>
            <div class="col-md-4">
              <p class="well well-sm">
                <b>Questions? Contact Mindful Health</b>
                <a href="#" class="btn btn-xs pull-right btn-info">Contact Us</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    </td>
    </tr>
    </tbody>
    </table>
    </span>